/* Generated By:JavaCC: Do not edit this line. yangTreeConstants.java Version 5.0 */
package org.adtran.yang.parser.helpers;

public interface yangTreeConstants
{
  public int JJTVOID = 0;
  public int JJTMODULE = 1;
  public int JJTSUBMODULE = 2;
  public int JJTYANGVERSION = 3;
  public int JJTIMPORT = 4;
  public int JJTINCLUDE = 5;
  public int JJTNAMESPACE = 6;
  public int JJTPREFIX = 7;
  public int JJTBELONG = 8;
  public int JJTORGANIZATION = 9;
  public int JJTCONTACT = 10;
  public int JJTDESCRIPTION = 11;
  public int JJTREFERENCE = 12;
  public int JJTUNITS = 13;
  public int JJTREVISION = 14;
  public int JJTEXTENSION = 15;
  public int JJTARGUMENT = 16;
  public int JJTYIN = 17;
  public int JJTIDENTITY = 18;
  public int JJTBASE = 19;
  public int JJTFEATURE = 20;
  public int JJTIFFEATURE = 21;
  public int JJTTYPEDEF = 22;
  public int JJTTYPE = 23;
  public int JJTRANGE = 24;
  public int JJTDECIMAL64SPEC = 25;
  public int JJTSTRINGRESTRICTION = 26;
  public int JJTLENGTH = 27;
  public int JJTPATTERN = 28;
  public int JJTDEFAULT = 29;
  public int JJTENUM = 30;
  public int JJTLEAFREFSPECIFICATION = 31;
  public int JJTPATH = 32;
  public int JJTUNIONSPECIFICATION = 33;
  public int JJTBITSPECIFICATION = 34;
  public int JJTBIT = 35;
  public int JJTPOSITION = 36;
  public int JJTSTATUS = 37;
  public int JJTCONFIG = 38;
  public int JJTMANDATORY = 39;
  public int JJTPRESENCE = 40;
  public int JJTORDEREDBY = 41;
  public int JJTMUST = 42;
  public int JJTERRORMESSAGE = 43;
  public int JJTERRORAPPT = 44;
  public int JJTMINELEMENT = 45;
  public int JJTMAXELEMENT = 46;
  public int JJTVALUE = 47;
  public int JJTGROUPING = 48;
  public int JJTCONTAINER = 49;
  public int JJTLEAF = 50;
  public int JJTLEAFLIST = 51;
  public int JJTLIST = 52;
  public int JJTKEY = 53;
  public int JJTUNIQUE = 54;
  public int JJTCHOICE = 55;
  public int JJTCASE = 56;
  public int JJTANYXML = 57;
  public int JJTUSES = 58;
  public int JJTREFINEANYNODE = 59;
  public int JJTREFINECONTAINER = 60;
  public int JJTREFINELEAF = 61;
  public int JJTREFINELEAFLIST = 62;
  public int JJTREFINELIST = 63;
  public int JJTREFINECHOICE = 64;
  public int JJTREFINECASE = 65;
  public int JJTREFINEANYXML = 66;
  public int JJTUSESAUGMENT = 67;
  public int JJTAUGMENT = 68;
  public int JJTUNKNOWN = 69;
  public int JJTWHEN = 70;
  public int JJTRPC = 71;
  public int JJTINPUT = 72;
  public int JJTOUTPUT = 73;
  public int JJTNOTIFICATION = 74;
  public int JJTDEVIATION = 75;
  public int JJTDEVIATENOTSUPPORTED = 76;
  public int JJTDEVIATEADD = 77;
  public int JJTDEVIATEDELETE = 78;
  public int JJTDEVIATEREPLACE = 79;


  public String[] jjtNodeName = {
    "void",
    "Module",
    "SubModule",
    "YangVersion",
    "Import",
    "Include",
    "NameSpace",
    "Prefix",
    "Belong",
    "Organization",
    "Contact",
    "Description",
    "Reference",
    "Units",
    "Revision",
    "Extension",
    "Argument",
    "Yin",
    "Identity",
    "Base",
    "Feature",
    "IfFeature",
    "TypeDef",
    "Type",
    "Range",
    "Decimal64Spec",
    "StringRestriction",
    "Length",
    "Pattern",
    "Default",
    "Enum",
    "LeafRefSpecification",
    "Path",
    "UnionSpecification",
    "BitSpecification",
    "Bit",
    "Position",
    "Status",
    "Config",
    "Mandatory",
    "Presence",
    "OrderedBy",
    "Must",
    "ErrorMessage",
    "ErrorAppt",
    "MinElement",
    "MaxElement",
    "Value",
    "Grouping",
    "Container",
    "Leaf",
    "LeafList",
    "List",
    "Key",
    "Unique",
    "Choice",
    "Case",
    "AnyXml",
    "Uses",
    "RefineAnyNode",
    "RefineContainer",
    "RefineLeaf",
    "RefineLeafList",
    "RefineList",
    "RefineChoice",
    "RefineCase",
    "RefineAnyXml",
    "UsesAugment",
    "Augment",
    "Unknown",
    "When",
    "Rpc",
    "Input",
    "Output",
    "Notification",
    "Deviation",
    "DeviateNotSupported",
    "DeviateAdd",
    "DeviateDelete",
    "DeviateReplace",
  };
}
/* JavaCC - OriginalChecksum=09b3673239e998192bbd78e3f5a671a6 (do not edit this line) */
